import type { Crop } from "../types.ts";

export const crops: Crop[] = [
  // Data in Spanish for Spain region, only vegetables
  // Source: Ministerio de Agricultura de España
  {
    name: "chard",
    category: "vegetable",
    seasonFrom: 7,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "garlic",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "artichoke",
    category: "vegetable",
    seasonFrom: 11,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "celery",
    category: "vegetable",
    seasonFrom: 10,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "eggplant",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "broccoli",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 5,
    yearRound: false,
  },
  {
    name: "zucchini",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "pumpkin",
    category: "vegetable",
    seasonFrom: 8,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "cardoon",
    category: "vegetable",
    seasonFrom: 11,
    seasonTo: 0,
    yearRound: false,
  },
  {
    name: "onion",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "redCabbage",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 1,
    yearRound: false,
  },
  {
    name: "cauliflower",
    category: "vegetable",
    seasonFrom: 8,
    seasonTo: 3,
    yearRound: false,
  },
  {
    name: "endive",
    category: "vegetable",
    seasonFrom: 8,
    seasonTo: 10,
    yearRound: false,
  },
  {
    name: "escarole",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 3,
    yearRound: false,
  },
  {
    name: "greenAsparagus",
    category: "vegetable",
    seasonFrom: 2,
    seasonTo: 5,
    yearRound: false,
  },
  {
    name: "spinach",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 5,
    yearRound: false,
  },
  {
    name: "pea",
    category: "vegetable",
    seasonFrom: 4,
    seasonTo: 5,
    yearRound: false,
  },
  {
    name: "broadBean",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "greenBean",
    category: "vegetable",
    seasonFrom: 7,
    seasonTo: 9,
    yearRound: false,
  },
  {
    name: "lettuce",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "turnip",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 11,
    yearRound: false,
  },
  {
    name: "cucumber",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "pepper",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "leek",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "radish",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "beet",
    category: "vegetable",
    seasonFrom: 7,
    seasonTo: 9,
    yearRound: false,
  },
  {
    name: "cabbage",
    category: "vegetable",
    seasonFrom: 8,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "tomato",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "carrot",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
];
