import type { Crop } from "../types.ts";

export const crops: Crop[] = [
  // Data for Spain region
  // Source: Ministerio de Agricultura de España

  // Vegetables
  {
    name: "chard",
    category: "vegetable",
    seasonFrom: 7,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "garlic",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "artichoke",
    category: "vegetable",
    seasonFrom: 11,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "celery",
    category: "vegetable",
    seasonFrom: 10,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "eggplant",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "broccoli",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 5,
    yearRound: false,
  },
  {
    name: "zucchini",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "pumpkin",
    category: "vegetable",
    seasonFrom: 8,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "cardoon",
    category: "vegetable",
    seasonFrom: 11,
    seasonTo: 0,
    yearRound: false,
  },
  {
    name: "onion",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "redCabbage",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 1,
    yearRound: false,
  },
  {
    name: "cauliflower",
    category: "vegetable",
    seasonFrom: 8,
    seasonTo: 3,
    yearRound: false,
  },
  {
    name: "endive",
    category: "vegetable",
    seasonFrom: 8,
    seasonTo: 10,
    yearRound: false,
  },
  {
    name: "escarole",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 3,
    yearRound: false,
  },
  {
    name: "greenAsparagus",
    category: "vegetable",
    seasonFrom: 2,
    seasonTo: 5,
    yearRound: false,
  },
  {
    name: "spinach",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 5,
    yearRound: false,
  },
  {
    name: "pea",
    category: "vegetable",
    seasonFrom: 4,
    seasonTo: 5,
    yearRound: false,
  },
  {
    name: "broadBean",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "greenBean",
    category: "vegetable",
    seasonFrom: 7,
    seasonTo: 9,
    yearRound: false,
  },
  {
    name: "lettuce",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "turnip",
    category: "vegetable",
    seasonFrom: 9,
    seasonTo: 11,
    yearRound: false,
  },
  {
    name: "cucumber",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "pepper",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "leek",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "radish",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "beet",
    category: "vegetable",
    seasonFrom: 7,
    seasonTo: 9,
    yearRound: false,
  },
  {
    name: "cabbage",
    category: "vegetable",
    seasonFrom: 8,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "tomato",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "carrot",
    category: "vegetable",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },

  // Fruits
  {
    name: "avocado",
    category: "fruit",
    seasonFrom: 10,
    seasonTo: 3,
    yearRound: false,
  },
  {
    name: "apricot",
    category: "fruit",
    seasonFrom: 4,
    seasonTo: 7,
    yearRound: false,
  },
  {
    name: "breva",
    category: "fruit",
    seasonFrom: 5,
    seasonTo: 6,
    yearRound: false,
  },
  {
    name: "persimmon",
    category: "fruit",
    seasonFrom: 9,
    seasonTo: 11,
    yearRound: false,
  },
  {
    name: "cherry",
    category: "fruit",
    seasonFrom: 4,
    seasonTo: 6,
    yearRound: false,
  },
  {
    name: "cherimoya",
    category: "fruit",
    seasonFrom: 9,
    seasonTo: 11,
    yearRound: false,
  },
  {
    name: "plum",
    category: "fruit",
    seasonFrom: 5,
    seasonTo: 7,
    yearRound: false,
  },
  {
    name: "raspberry",
    category: "fruit",
    seasonFrom: 9,
    seasonTo: 3,
    yearRound: false,
  },
  {
    name: "strawberry",
    category: "fruit",
    seasonFrom: 0,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "pomegranate",
    category: "fruit",
    seasonFrom: 9,
    seasonTo: 10,
    yearRound: false,
  },
  {
    name: "fig",
    category: "fruit",
    seasonFrom: 6,
    seasonTo: 8,
    yearRound: false,
  },
  {
    name: "kiwi",
    category: "fruit",
    seasonFrom: 9,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "lemon",
    category: "fruit",
    seasonFrom: 10,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "mandarin",
    category: "fruit",
    seasonFrom: 9,
    seasonTo: 3,
    yearRound: false,
  },
  {
    name: "mango",
    category: "fruit",
    seasonFrom: 7,
    seasonTo: 10,
    yearRound: false,
  },
  {
    name: "apple",
    category: "fruit",
    seasonFrom: 8,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "peach",
    category: "fruit",
    seasonFrom: 4,
    seasonTo: 8,
    yearRound: false,
  },
  {
    name: "melon",
    category: "fruit",
    seasonFrom: 5,
    seasonTo: 7,
    yearRound: false,
  },
  {
    name: "quince",
    category: "fruit",
    seasonFrom: 7,
    seasonTo: 8,
    yearRound: false,
  },
  {
    name: "orange",
    category: "fruit",
    seasonFrom: 10,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "nectarine",
    category: "fruit",
    seasonFrom: 4,
    seasonTo: 8,
    yearRound: false,
  },
  {
    name: "loquat",
    category: "fruit",
    seasonFrom: 3,
    seasonTo: 4,
    yearRound: false,
  },
  {
    name: "flatPeach",
    category: "fruit",
    seasonFrom: 5,
    seasonTo: 7,
    yearRound: false,
  },
  {
    name: "pear",
    category: "fruit",
    seasonFrom: 6,
    seasonTo: 2,
    yearRound: false,
  },
  {
    name: "banana",
    category: "fruit",
    seasonFrom: 0,
    seasonTo: 11,
    yearRound: true,
  },
  {
    name: "grapefruit",
    category: "fruit",
    seasonFrom: 11,
    seasonTo: 3,
    yearRound: false,
  },
  {
    name: "watermelon",
    category: "fruit",
    seasonFrom: 5,
    seasonTo: 7,
    yearRound: false,
  },
  {
    name: "grape",
    category: "fruit",
    seasonFrom: 8,
    seasonTo: 11,
    yearRound: false,
  },
];
