const VEGETABLE_LABELS = {
  chard: "acelga",
  garlic: "ajo",
  artichoke: "alcachofa",
  celery: "apio",
  eggplant: "berenjena",
  broccoli: "brócoli",
  zucchini: "calabacín",
  pumpkin: "calabaza",
  cardoon: "cardo",
  onion: "cebolla",
  redCabbage: "col lombarda",
  cauliflower: "coliflor",
  endive: "endibia",
  escarole: "escarola",
  greenAsparagus: "espárrago verde",
  spinach: "espinaca",
  pea: "guisante",
  broadBean: "haba",
  greenBean: "judía verde",
  lettuce: "lechuga",
  turnip: "nabo",
  cucumber: "pepino",
  pepper: "pimiento",
  leek: "puerro",
  radish: "rábano",
  beet: "remolacha",
  cabbage: "repollo",
  tomato: "tomate",
  carrot: "zanahoria",
};

const FRUIT_LABELS = {
  avocado: "aguacate",
  apricot: "albaricoque",
  breva: "breva",
  persimmon: "caqui",
  cherry: "cereza",
  cherimoya: "chirimoya",
  plum: "ciruela",
  raspberry: "frambuesa",
  strawberry: "fresa",
  pomegranate: "granada",
  fig: "higo",
  kiwi: "kiwi",
  lemon: "limón",
  mandarin: "mandarina",
  mango: "mango",
  apple: "manzana",
  peach: "melocotón",
  melon: "melón",
  quince: "membrillo",
  orange: "naranja",
  nectarine: "nectarina",
  loquat: "níspero",
  flatPeach: "paraguaya",
  pear: "pera",
  banana: "plátano",
  grapefruit: "pomelo",
  watermelon: "sandía",
  grape: "uva",
};

export const CROPS_LABELS = {
  ...VEGETABLE_LABELS,
  ...FRUIT_LABELS,
};
