export const CROPS_LABELS = {
  chard: "acelga",
  garlic: "ajo",
  artichoke: "alcachofa",
  celery: "apio",
  eggplant: "berenjena",
  broccoli: "brócoli",
  zucchini: "calabacín",
  pumpkin: "calabaza",
  cardoon: "cardo",
  onion: "cebolla",
  redCabbage: "col lombarda",
  cauliflower: "coliflor",
  endive: "endibia",
  escarole: "escarola",
  greenAsparagus: "espárrago verde",
  spinach: "espinaca",
  pea: "guisante",
  broadBean: "haba",
  greenBean: "judía verde",
  lettuce: "lechuga",
  turnip: "nabo",
  cucumber: "pepino",
  pepper: "pimiento",
  leek: "puerro",
  radish: "rábano",
  beet: "remolacha",
  cabbage: "repollo",
  tomato: "tomate",
  carrot: "zanahoria",
};
